### ISSUE TITLE
Sprite sizes vary depending on Generation they came from

### ISSUE THREAD

**Issue by omnibombulator** [adamsb0303/Shiny_Hunt_Tracker#1]
As shown here: [Imgur Link](https://i.imgur.com/Pf8Km4Y.jpg)

If a sprite is from SWSH, it is much larger (by more than double in some cases) in pixel size.

Suggestions include:
Changing "Scale" to change the size in pixels rather than a percentage based on the sprite size.
Or using/adding the option to use the sprites found in Pokemon HOME (Found here by generations: [1](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-1-r128/) | [2](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-2-r129/) | [3](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-3-r130/) | [4](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-4-r131/) | [5](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-5-r132/) | [6](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-6-r133/) | [7](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-7-r134/) | [8](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-8-r135/) | [Misc](https://projectpokemon.org/docs/spriteindex_148/home-sprites-gen-unknown-r127/) )

**Comment by adamsb0303** [comment]
Thanks for the suggestion! I've also found this annoying, so I'll see what I can do.

**Comment by adamsb0303** [comment]
Just released an update that automatically scales based on the size of the previous image. For example, if you are hunting Natu or another all pokemon, it will take the biggest of the height or width (in this case height) and scale the next pokemon to fit to that. Thanks again for the suggestion!
